# Your workflow name.
name: Pre-production to Heroku

# Run workflow on every push to master branch.
on:
  push:
    branches: [release]

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    environment: pre-release
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Heroku
        run: |
          echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=${{ secrets.HEROKU_EMAIL }} registry.heroku.com --password-stdin
        
      - name: Build docker image
        run: |
          docker build . --tag registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      - name: Push image to Heroku 
        run: |
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      - name: Release to Heroku
        run: |
          heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
      # Release docker image to Heroku
      # - name: Build Push Release to Heroku
      #   uses: gonuit/heroku-docker-deploy@v1.3.3
      #   with:
      #     email: ${{ secrets.HEROKU_EMAIL }}
      #     heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
      #     heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          